[DO NOT MERGE] Drupal rivers configurations
searchisko/configuration pull request #87
Opened 2017-01-27 22:05 UTC by Dantheman720

@unibrew - I wasn't able to get the indexer running on staging for some reason. I pushed up the provider and the rest of the configurations (outside of the river) should be the same. http://dcp.stage.jboss.org/v2/rest/indexer/jbossdeveloper_book/_status. I'm sure I did something wrong here. Everything works fine locally, but since I don't have visibility to the dcp log files, I don't really know what I did wrong here.

Anyway, perhaps we can discuss early next week?

2017-01-29 11:10 UTC, unibrew commented
It seems that your push of provider was not successful, please retry, if still wrong, let me know I'll try myself - http://dcp.stage.jboss.org/v2/rest/provider/jboss-developer

2017-02-10 09:22 UTC, unibrew commented on rivers/books_drupal.json
> +        "name"     : "String to ISO Date formatter",
I think you've reimplemented in JS this preprocessor https://github.com/searchisko/structured-content-tools/blob/master/src/main/java/org/jboss/elasticsearch/tools/content/LongToTimestampValuePreprocessor.java

2017-02-10 09:24 UTC, unibrew commented on rivers/books_drupal.json
> +      "authors": {"remote_field": "prep_sys_authors"},
Not sure if intentionally you prep sys authors but then put them in authors field instead of sys_authors.

2017-02-10 09:26 UTC, unibrew commented on rivers/books_drupal.json
> +      "published_date": {"remote_field": "test_sys_created_date"},
This field seems redundant to sys_created, plus 'test_sys_created_date' doesn't exist.

2017-02-15 02:11 UTC, Dantheman720 commented
@unibrew - So, I think this is about ready. Can we go through it tomorrow and discuss the sys_contributors further? I wasn't able to look into it much today, but I've been hung up on it for quite of a bit.

For the LongToTimestamp conversion, it wasn't actually being converted to a timestamp so I decided to use JS to parse it. If that doesn't work, I can definitely change it.

2017-02-17 00:03 UTC, Dantheman720 commented
@unibrew - Ok! I think we're good to go!

2017-02-17 00:05 UTC, unibrew commented
Is the same on our stage? I'd like to take the last look on the data before merging tomorrow.

2017-02-17 00:14 UTC, Dantheman720 commented
I'll push each of those up to staging. Though...we don't have the books and connectors in production on the drupal side yet. I need to get those in before we merge otherwise it'll just pull empty data sets. I'll do that first thing tomorrow morning.

2017-02-17 00:20 UTC, unibrew commented
ok, understood. We'll see how it works on staging but I'm waiting for your green light till this gets pushed to prod. Thanks!

2017-02-17 00:22 UTC, Dantheman720 commented
Sounds like a plan!

2017-02-17 00:43 UTC, Dantheman720 commented
Well, staging is up to date now. I'll work on production tomorrow.

On Thu, Feb 16, 2017 at 4:20 PM, Rysiek <notifications@github.com> wrote:

> ok, understood. We'll see how it works on staging but I'm waiting for your
> green light till this gets pushed to prod. Thanks!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/searchisko/configuration/pull/87#issuecomment-280509501>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AA5SqGRZQH6qHcmiJ8o8NLyzyl4cT2zEks5rdOe2gaJpZM4LwQ-P>
> .
>

2017-02-17 09:43 UTC, unibrew commented
This space key issue that Libor raised against SO is present here as well. We need to correct it.

2017-02-17 22:46 UTC, Dantheman720 commented
@unibrew - So, I think we're good now? I pushed the new configs to staging.

2017-02-17 22:47 UTC, Dantheman720 commented
I haven't moved anything to production yet, since I'm not entirely sure this is what's required.

2017-02-17 22:50 UTC, unibrew commented
Thank you, I'll take a final look on the data on staging on Monday. Is everything production ready on Drupal side? Last time you've mentioned that some work needs to be done before pushing this config to prod.
Also, would you mind sending me an email with the command that will add the correct configuration for apikey for prod. I suppose you have it cached somewhere, I wouldn't have to "invent" it ;)

2017-02-17 22:53 UTC, Dantheman720 commented
I need https://github.com/redhat-developer/developers.redhat.com/pull/1756 merged before it's prod ready.

2017-02-20 12:34 UTC, unibrew commented
Dan, you need to have a look on errors /v2/rest/indexer/_all/_status. There are date format issues for sys_created. I stopped those 3 rivers so that they don't spam logs with those errors. Remember to restart them after correcting the config.

2017-02-20 16:32 UTC, Dantheman720 commented
Will do!

On Mon, Feb 20, 2017 at 4:34 AM, Rysiek <notifications@github.com> wrote:

> Dan, you need to have a look on errors /v2/rest/indexer/_all/_status.
> There are date format issues for sys_created. I stopped those 3 rivers so
> that they don't spam logs with those errors. Remember to restart them after
> correcting the config.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/searchisko/configuration/pull/87#issuecomment-281068149>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AA5SqPt0vWsiixgHkWR8ZFcCY7TRVXYCks5reYhZgaJpZM4LwQ-P>
> .
>

2017-02-22 17:52 UTC, unibrew commented
@lkrzyzanek or @velias : guys, any of you want to review this as well before I merge?

2017-02-22 19:31 UTC, velias commented
I miss prefix jbossdeveloper_ in river names to keep naming conventions

2017-02-23 01:06 UTC, Dantheman720 commented
I think we should be good to go now. The data is in production for books and connectors. We are not pushing old events.

2017-02-23 09:42 UTC, lkrzyzanek commented
Yep I can review. Where is JIRA issue for this with description what it suppose to do?

2017-02-23 16:14 UTC, Dantheman720 commented
This was the JIRA ticket I've been working from -
https://issues.jboss.org/browse/DEVELOPER-3809. It doesn't really get into
the technical requirements of the rivers config, but it defines our
requirements for RHD.

On Thu, Feb 23, 2017 at 1:42 AM, Libor Krzyzanek <notifications@github.com>
wrote:

> Yep I can review. Where is JIRA issue for this with description what it
> suppose to do?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/searchisko/configuration/pull/87#issuecomment-281943962>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AA5SqLOC53qW2bTx7g2RJ7996XXGFJpJks5rfVR4gaJpZM4LwQ-P>
> .
>

2017-02-24 09:02 UTC, lkrzyzanek commented
Review jira issue: https://issues.jboss.org/browse/ORG-3616

2017-02-28 13:00 UTC, lkrzyzanek requested changes
1. General comments 
 * `urlGetDocuments` contains http:// I would suggest to move http to the configuration. It would be more flexible in case of https change
 * rivers uses copying data from source field to "prep_something" in cases  where it's not necessary to do so. When you don't need to manipulate data in preprocessor then directly copy data from remote field within index.fields definition. It would keep things more cleaner. 
* timeout - 20secs. Is production fast enough? Consider increasing to 60 sec
* all mappings "data_something" doesn't have mapping for `space_key`
````
"space_key" : {"type" : "string", "analyzer" : "keyword"},
````

2. Mapping for Books - mappings/data_jbossdeveloper_book/jbossdeveloper_book.json 
* needs mapping for `published_date` as date

3. Mapping for Connector mappings/data_jbossdeveloper_connector/jbossdeveloper_connector.json
* priority needs mapping to be `integer` otherwise sorting doesn't work properly
* I'm also wondering what the value of priority means. 50 > 10 ? In that case registered query sorts based on it incorrectly

4. Events
I'm not sure if field_data_tags works correctly. Source contains string like "Atomic, CDK, Containers". Check if ES parses it to the array out of the box.

2017-02-28 13:22 UTC, lkrzyzanek commented
Btw. books doesn't have relation to product so I raised this issue DEVELOPER-3915. But it can be fixed in separate PR.

2017-02-28 17:11 UTC, Dantheman720 commented
@lkrzyzanek - "urlGetDocuments contains http:// I would suggest to move http to the configuration. It would be more flexible in case of https change."

I tried leaving the http:// out and for some reason, I kept getting error messages. I guess that could've been related to parsing.  Other than that, I'll make the suggested changes.

2017-03-03 07:48 UTC, lkrzyzanek reviewed
I think it looks good now. Try those rivers in  dcp stage and I'll do final review of final content in stage.
Thanks.

2017-03-03 07:48 UTC, lkrzyzanek commented on mappings/data_jbossdeveloper_connector/jbossdeveloper_connector.json
> +      "field_connector_priority": {
The final property is `priority` not `field_connector_priority`

2017-03-03 16:20 UTC, Dantheman720 commented
Good deal. I'll make that switch. I wasn't 100% sure on that.

On Thu, Mar 2, 2017 at 11:48 PM, Libor Krzyzanek <notifications@github.com>
wrote:

> *@lkrzyzanek* commented on this pull request.
>
> I think it looks good now. Try those rivers in dcp stage and I'll do final
> review of final content in stage.
> Thanks.
> ------------------------------
>
> In mappings/data_jbossdeveloper_connector/jbossdeveloper_connector.json
> <https://github.com/searchisko/configuration/pull/87#discussion_r104102716>
> :
>
> >        "sys_title": {
>          "type": "string",
>          "include_in_all": true,
>          "_boost": 1.5
> +      },
> +      "field_connector_priority": {
>
> The final property is priority not field_connector_priority
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/searchisko/configuration/pull/87#pullrequestreview-24918689>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AA5SqCFI74nxIcdOg8TeJN7auqVyvdb0ks5rh8XSgaJpZM4LwQ-P>
> .
>

2017-03-07 15:51 UTC, Dantheman720 commented
@lkrzyzanek - Alright, everything is in staging now (including the fix). Hopefully we're good to merge now.

2017-03-08 08:39 UTC, lkrzyzanek approved these changes

2017-03-08 08:39 UTC, lkrzyzanek commented
Looks good to me know. I think we can merge.
What is the release steps in PROD ?

2017-03-08 14:46 UTC, Dantheman720 commented
@unibrew - I think we're good now! Do you need me to do anything for the release?

2017-03-08 17:19 UTC, unibrew commented
Guys, I'm on PTO till Monday and that's the earliest I can look into this. Unless Libor handles this before.

2017-03-09 10:06 UTC, lkrzyzanek commented
@Dantheman720 what are steps you did on staging. We should do same in PROD. I'm looking for something like this: https://issues.jboss.org/browse/ORG-3611?focusedCommentId=13363857&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13363857

2017-03-09 17:35 UTC, Dantheman720 commented
@lkrzyzanek - I haven't worked with production before. I basically just blew everything out for each index and river.  The list that you provided on https://issues.jboss.org/browse/ORG-3611?focusedCommentId=13363857&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel looks pretty similar to what I did (actually it's more elegant than what I did).

2017-03-10 08:47 UTC, merged

2017-03-10 08:51 UTC, lkrzyzanek commented
Ok, I've merged the PR but we would still need exact release steps.
@Dantheman720 can you work on this? I mean just list of commands needed.
I guess it will be very similar what I used before so feel free to copy :-)

2017-03-14 16:46 UTC, Dantheman720 commented
@unibrew - Do you need me to do anything here? I've not done anything related to release before.

2017-03-15 14:55 UTC, unibrew commented
@Dantheman720 Please have a look if I didn't miss anything in the release steps https://issues.jboss.org/browse/ORG-3626

2017-03-15 18:43 UTC, unibrew commented
This is now pushed to prod. Thank you all for the PR and reviews.